### ISSUE TITLE
Connection ERROR

### ISSUE THREAD

**Issue by ghost** [muneebwanee/InstaReporter#1]
[ OK ] Modules loaded!
 
[ ? ] Would you like to use a proxy? [Y/N]: n

[ * ] 1 - Report the profile. 
[ * ] 2 - Report a video. 
[ ? ] Please select the complaint method: 1

[ ? ] Enter the username of the person you want to report: hydra_bajju_33

[ * ] 1. Transaction Opened! 
[ * ] 2. Transaction Opened! 
[ * ] 3. Transaction Opened! 
[ * ] 4. Transaction Opened! 
[ * ] 5. Transaction Opened! 

[ OK ] Connection error has occurred! 
[ OK ] Connection error has occurred! 
[ OK ] Connection error has occurred! 
[ OK ] Connection error has occurred! 
[ OK ] Connection error has occurred! 
[ OK ] Connection error has occurred! 
[ OK ] Connection error has occurred! 
[ OK ] Connection error has occurred! 
[ OK ] Connection error has occurred! 
[ OK ] Connection error has occurred! 
[ OK ] Connection error has occurred! 
[ OK ] Connection error has occurred! 
[ OK ] Connection error has occurred! 
[ OK ] Connection error has occurred! 
[ OK ] Connection error has occurred! 
[ OK ] Connection error has occurred! 
[ OK ] Connection error has occurred! 
[ OK ] Connection error has occurred! 
[ OK ] Connection error has occurred! 
[ OK ] Connection error has occurred! 
[ OK ] Connection error has occurred! 
[ OK ] Connection error has occurred! 
[ OK ] Connection error has occurred! 
[ OK ] Connection error has occurred! 
[ OK ] Connection error has occurred! 
[ OK ] Connection error has occurred! 
[ OK ] Connection error has occurred! 
[ OK ] Connection error has occurred! 
[ OK ] Connection error has occurred! 
[ OK ] Connection error has occurred! 
[ OK ] Connection error has occurred! 
[ OK ] Connection error has occurred! 
[ OK ] Connection error has occurred! 
[ OK ] Connection error has occurred! 
[ OK ] Connection error has occurred! 
[ OK ] Connection error has occurred! 
[ OK ] Connection error has occurred! 
[ OK ] Connection error has occurred! 
[ OK ] Connection error has occurred! 
[ OK ] Connection error has occurred! 
[ OK ] Connection error has occurred! 
[ OK ] Connection error has occurred! 
[ OK ] Connection error has occurred! 
[ OK ] Connection error has occurred! 
[ OK ] Connection error has occurred! 
[ OK ] Connection error has occurred! 
[ OK ] Connection error has occurred! 
[ OK ] Connection error has occurred! 
[ OK ] Connection error has occurred! 
[ OK ] Connection error has occurred!

**Comment by muneebwanee** [comment]
Buddy, I am working on it. will fix it soon.

**Comment by HaykMarkosyan** [comment]
[ * ] 1. Transaction Opened! 
Traceback (most recent call last):
  File "/home/kali/Desktop/instareporter/InstaReporter/InstaReporter.py", line 147, in <module>
    main()
  File "/home/kali/Desktop/instareporter/InstaReporter/InstaReporter.py", line 140, in main
    profile_attack(proxies)
  File "/home/kali/Desktop/instareporter/InstaReporter/InstaReporter.py", line 92, in profile_attack
    if (k == 5): print()
UnboundLocalError: local variable 'k' referenced before assignment
[ ERR ] Connection error has occurred! (FacebookRequestsError) 
[ ERR ] Connection error has occurred! (FacebookRequestsError) 
[ ERR ] Connection error has occurred! (FacebookRequestsError) 
[ ERR ] Connection error has occurred! (FacebookRequestsError) 
[ ERR ] Connection error has occurred! (FacebookRequestsError) 
[ ERR ] Connection error has occurred! (FacebookRequestsError) 
[ ERR ] Connection error has occurred! (FacebookRequestsError) 
[ ERR ] Connection error has occurred! (FacebookRequestsError) 
[ ERR ] Connection error has occurred! (FacebookRequestsError) 
[ ERR ] Connection error has occurred! (FacebookRequestsError)

**Comment by ayushsahu4** [comment]
[ ERR ] Connection error! (FacebookRequestsError)
[ ERR ] Connection error! (FacebookRequestsError)
[ ERR ] Connection error! (FacebookRequestsError)
[ ERR ] Connection error! (FacebookRequestsError)
[ ERR ] Connection error! (FacebookRequestsError)
[ ERR ] Connection error! (FacebookRequestsError)
[ ERR ] Connection error! (FacebookRequestsError)
[ ERR ] Connection error! (FacebookRequestsError)
[ ERR ] Connection error! (FacebookRequestsError)
[ ERR ] Connection error! (FacebookRequestsError)
[ ERR ] Connection error! (FacebookRequestsError)
[ ERR ] Connection error! (FacebookRequestsError)
[ ERR ] Connection error! (FacebookRequestsError)
[ ERR ] Connection error! (FacebookRequestsError)
[ ERR ] Connection error! (FacebookRequestsError)
[ ERR ] Connection error! (FacebookRequestsError)
[ ERR ] Connection error! (FacebookRequestsError)


Please Brother Solve this. thank you

**Comment by KlasH-Cats** [comment]
We are in 2025 and still not resolved bro
